language: node_js
node_js: 10

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - ng build --prod
  - npm install codecov -g

after_success:
  - codecov
  # - yarn packagr
  # - yarn publish

notifications:
  email:
    on_failure: change
    on_success: change